[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    micro/micro-ROS
build_flags =
    -D MICRO_ROS_TRANSPORT=UART
    -D MICRO_ROS_UART_BUADRATE=115200
    -D MICRO_ROS_UART_TX_PIN=GPIO_NUM_1
    -D MICRO_ROS_UART_RX_PIN=GPIO_NUM_3
    -D MICRO_ROS_UART_PORT=1
monitor_speed = 115200